import Head from 'next/head'

export async function getStaticProps() {
  const today = new Date();
  return {
    props: {
      datetime: today.toISOString()
    }
  }
}

export default function Home({datetime}) {
  return (
    <>
      <Head>
        <title>ISR Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>
          Last updated: {datetime}
        </p>
      </main>
    </>
  )
}
